name: "Run notebooks"

on:
  push:
    branches:
      - "**"
      # - "!main"
      # - "!gh-pages"

env:
  # disable keyring (https://github.com/actions/runner-images/issues/6185):
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: sudo apt-get install poppler-utils
      - name: Install poetry
        run: pipx install poetry==1.6.1
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install package and dependencies
        run: poetry install
        shell: bash
      - name: Run notebooks
        env:
          DEEPSEARCH_HOST: ${{ secrets.DEEPSEARCH_HOST }}
          DEEPSEARCH_USERNAME: ${{ secrets.DEEPSEARCH_USERNAME }}
          DEEPSEARCH_API_KEY: ${{ secrets.DEEPSEARCH_API_KEY }}
          DEEPSEARCH_VERIFY_SSL: ${{ secrets.DEEPSEARCH_VERIFY_SSL }}
          DS_NB_PROJ_KEY: ${{ secrets.DS_NB_PROJ_KEY }}
          DS_NR_EXCLUDED: ${{ secrets.DS_NR_EXCLUDED }}
        run: poetry run python -m nbrunner.nb_runner
